tags:
  tag_0:
    id: 0
    frame_id: tag_0
    x: 1.78
    y: -2.55
    z: 0.50
    roll: 0.0
    pitch: 0.0
    yaw: 1.57
    size: 0.35
  tag_1:
    id: 1
    frame_id: tag_1
    x: 0.52
    y: -11.03
    z: 0.50
    roll: 0.0
    pitch: 0.0
    yaw: -1.57
    size: 0.35
  tag_2:
    id: 2
    frame_id: tag_2
    x: 3.76
    y: -6.04
    z: 0.50
    roll: 0.0
    pitch: 0.0
    yaw: 3.14
    size: 0.35
  tag_3:
    id: 3
    frame_id: tag_3
    x: 0.20
    y: -7.50
    z: 0.50
    roll: 0.0
    pitch: 0.0
    yaw: -1.57
    size: 0.35
  tag_4:
    id: 4
    frame_id: tag_4
    x: 9.32
    y: 0.04
    z: 0.50
    roll: 0.0
    pitch: 0.0
    yaw: 1.57
    size: 0.35
  tag_5:
    id: 5
    frame_id: tag_5
    x: 8.78
    y: -8.53
    z: 0.50
    roll: 0.0
    pitch: 0.0
    yaw: 1.57
    size: 0.35

ground_truth_leo2_to_leo1:
  x: 2.36
  y: -11.27
  yaw: 0.0
