slam_toolbox:
  ros__parameters:
    # --- ROS Parameters ---
    use_sim_time: true
    odom_frame: "leo1/odom"
    base_frame: "leo1/base_link"
    map_frame: "map"
    scan_topic: "/leo1/scan"

    # --- Mapping Mode ---
    mode: mapping

    # --- Scan Matching ---
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_time_interval: 0.0

    # --- Map Parameters ---
    resolution: 0.03
    max_laser_range: 20.0
    map_update_interval: 0.1
    transform_publish_period: 0.02

    # --- Performance & Optimization ---
    # Solver settings (Standard for most 2D Lidar)
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_preconditioner: "SCHUR_JACOBI"
    ceres_trust_strategy: "LEVENBERG_MARQUARDT"

    # Optimization/Loop Closure
    do_loop_closing: true
    loop_search_maximum_distance: 5.0
    loop_match_minimum_chain_size: 3
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Thresholds for when to add a new scan to the pose graph
    minimum_travel_distance: 0.001
    minimum_travel_heading: 0.05

    # --- Buffers and Limits ---
    tf_buffer_duration: 30.0
    transform_timeout: 0.5
    stack_size_to_use: 40000000 # Required for larger map serialization

    # --- Interactive Mode ---
    enable_interactive_mode: true